// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loegsdjbyazhlfrnfrlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvZWdzZGpieWF6aGxmcm5mcmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTkwNjIsImV4cCI6MjA2MjM3NTA2Mn0.VTBpHHMvQlRVN_nLTb94T34giI3idpcfYYgdGPtITrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);